# Ackermann steering controller configuration
ackermann_controller:
  type: "ackermann_steering_controller/AckermannSteeringController"
  front_left_wheel: "front_left_wheel_joint"
  front_right_wheel: "front_right_wheel_joint"
  rear_left_wheel: "rear_left_wheel_joint"
  rear_right_wheel: "rear_right_wheel_joint"
  wheel_separation: 2.0   # Distance between the left and right wheels
  wheel_radius: 0.2       # Radius of the wheels
  wheel_base: 2.0         # Distance between the front and rear wheels
  steer_angle_limit: 0.2  # Maximum steering angle
